apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-docs
resources:
- spinapp.yaml
images:
- name: flux-docs/build
  newname: ghcr.io/kingdon-ci/flux-docs/build # image:name
  newtag: updateme # image:tag
configurations:
- images-config.yaml
