---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: docs-infra
  namespace: default
spec:
  timeout: 1m0s
  retryInterval: 1m30s
  interval: 10m0s
  path: ./spin-infra
  prune: true
  wait: true
  sourceRef:
    kind: OCIRepository
    name: flux-docs
